-- Create the servicos table
create table if not exists public.servicos (
    id bigint generated by default as identity primary key,
    titulo text not null,
    emoji text,
    imagem text not null,
    descricao text not null,
    created_at timestamptz default now()
);

-- Set up Row Level Security (RLS)
alter table public.servicos enable row level security;

-- Create policies
create policy "Serviços são visíveis para todos"
    on public.servicos for select
    to public
    using (true);

create policy "Apenas usuários autenticados podem inserir serviços"
    on public.servicos for insert
    to authenticated
    with check (true);

create policy "Apenas usuários autenticados podem atualizar serviços"
    on public.servicos for update
    to authenticated
    using (true);

create policy "Apenas usuários autenticados podem deletar serviços"
    on public.servicos for delete
    to authenticated
    using (true);

-- Create storage bucket for servicos
insert into storage.buckets (id, name, public) 
values ('servicos', 'servicos', true);

-- Storage policy for public access to read images
create policy "Imagens são públicas"
    on storage.objects for select
    to public
    using ( bucket_id = 'servicos' );

-- Storage policy for authenticated users to upload images
create policy "Usuários autenticados podem fazer upload"
    on storage.objects for insert
    to authenticated
    with check ( bucket_id = 'servicos' );

-- Storage policy for authenticated users to update images
create policy "Usuários autenticados podem atualizar imagens"
    on storage.objects for update
    to authenticated
    with check ( bucket_id = 'servicos' );

-- Storage policy for authenticated users to delete images
create policy "Usuários autenticados podem deletar imagens"
    on storage.objects for delete
    to authenticated
    using ( bucket_id = 'servicos' );

-- Insert initial services
insert into public.servicos (titulo, emoji, imagem, descricao) values
    ('Massagem Relaxante', '👐💆‍♂️', '/massagem-relaxante.jpg', 'Uma experiência clássica e revigorante que alivia o estresse e as tensões musculares. Com movimentos suaves e contínuos, promove relaxamento profundo, melhora a circulação e proporciona uma sensação de leveza e bem-estar.'),
    ('Massagem Tântrica', '🔥💫', '/massagem-tantrica.jpg', 'Uma jornada sensorial que desperta os sentidos e desbloqueia a energia vital. Através de toques sutis e envolventes, essa massagem proporciona prazer, autoconhecimento e uma conexão mais profunda com o próprio corpo.'),
    ('Massagem Tailandesa', '🧘‍♂️🌿', '/massagem-tailandesa.jpg', 'Uma técnica milenar que combina alongamentos, pressões e manipulações inspiradas na yoga. Perfeita para aliviar tensões, melhorar a flexibilidade e restaurar o equilíbrio energético do corpo.'),
    ('Massagem Nurum', '✨🌊', '/massagem-nurum.jpg', 'Uma experiência exótica e extremamente prazerosa, onde a terapeuta desliza suavemente sobre o corpo do cliente utilizando um gel especial. Essa técnica proporciona relaxamento intenso e uma conexão sensorial única.'),
    ('Massagem Fast Relax', '⚡⏳', '/massagem-fast.jpg', 'Ideal para quem tem pouco tempo, mas precisa de um alívio imediato do estresse. Com técnicas rápidas e eficazes, essa massagem foca nas áreas de maior tensão, proporcionando relaxamento instantâneo em poucos minutos.'); 