create table "public"."analytics" (
    "id" bigint generated by default as identity not null,
    "tipo" text not null,
    "profissional_id" bigint references profissionais(id),
    "profissional_nome" text,
    "post_id" bigint references blog_posts(id),
    "servico_id" bigint references servicos(id),
    "timestamp" timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint analytics_pkey primary key (id)
);

-- Permitir que usuários anônimos insiram dados de analytics
create policy "Permitir inserção anônima de analytics"
on analytics for insert
to anon
with check (true);

-- Permitir que usuários anônimos leiam dados de analytics
create policy "Permitir leitura anônima de analytics"
on analytics for select
to anon
using (true);

-- Permitir que usuários autenticados leiam dados de analytics
create policy "Permitir leitura de analytics"
on analytics for select
to authenticated
using (true);

-- Habilitar RLS
alter table "public"."analytics" enable row level security;

